VocaDB/vocadb

- VocaDbWeb/Views/Help/Index.cshtml
Change to github link.
Small (and semi unnecessary) change, but I still thought I'd help out.
> Change to github link on help/about page

- VocaDbWeb/Views/Shared/Partials/_Footer.cshtml
The credit text "みゆ" in the footer is not displayed correctly due to the wrong encoding.
> Fix garbled credit text

- VocaDbWeb/App_Code/HtmlHelpers.cshtml
- VocaDbWeb/Code/Markdown/MarkdownParser.cs
- VocaDbWeb/Scripts/KnockoutExtensions/StopBinding.ts
- VocaDbWeb/Views/Album/Details.cshtml
Add StopBinding to all Markdown-formatted server-side rendered text.
> #542: ignore all markdown fields from KO binding

- VocaDbWeb/App_Code/PVHelpers.cshtml
The `cid` is in fact unnecessary for Bilibili iframe players (the `page` alone is sufficient for navigating in multi-page videos, see #494 ), and we can still enable the new `<iframe>` players without referring to `cid`s for songs who didn't got their `cid`s here (#495 ).
Bilibili playback controls will show up for `<iframe>`s larger than 480*360 (#372 ). If the frame is larger than the threshold, playback controls (29px in height) will start to show, and another two ad banners (one in the top, 48px in height; the other in the bottom, 38px in height) will also show up. My strategy would be simply masking the two ad banners away, so that we can get the playback controls back while also meeting the vocaDB size requirement (560*315).
> Fix Bili playback controls; iframe all Bili player

- VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs
- VocaDbWeb/Content/Styles/ExtLinks.css
- VocaDbWeb/Content/Styles/ExtLinks.less
1. Most newly added Bilibili user profiles for artists go like `http://space.bilibili.com/nnn`. It would be great convenient to have them automatically matched when adding songs.
2. Many major subdomains (even including "http(s)://www.bilibili.com/" itself!) cannot have the icon shown in vocadb's pages, which is ridiculous.
> Update the matcher for Bili user profile & Enable icons for all Bili subdomains

- VocaDbWeb/App_Code/PVHelpers.cshtml
The Bilibili iframe player has removed the top banner ads, so we remove the obsolete -48px top margin.
> Update Bilibili player outlay: remove top banner mask

- VocaDbWeb/VocaDbWeb.csproj
Removed pre-build events. Now that we have to manually use `npm run css-dev && npm run dev` for debug or `npm run css-prod && npm run prod` for release to compile static assets (e.g. less and ts files).
> Remove pre-build events

- VocaDbWeb.Core/VocaDbWeb.Core.csproj
> Enable unsafe binary serialization

- VocaDbWeb.Core/Views/Admin/ManageIPRules.cshtml
- VocaDbWeb/Views/Admin/ManageIPRules.cshtml
`JSON.parse` cannot parse `new Date()` and throws an `Uncaught SyntaxError`. I don't see any reason to set the third argument of `ToJS` to true.
> Fix ManageIPRules

- VocaDbWeb/wwwroot/Content/Styles/DarkAngel.less
Closes #602. I also added an invert filter to the GitHub icon:
^Before
^After
> #602 Text color has low contrast on Dark Angel theme

- Tests/Service/Helpers/ArtistExternalUrlParserTests.cs
- Tests/Service/Search/Artists/ArtistSearchTests.cs
- VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs
- VocaDbModel/Service/Search/Artists/ArtistSearch.cs
Closes #843.
I changed the suggested URL parser from `@{Twitter username}` to `t/{Twitter username}` because there are some artists who use @ at the beginning of their username (https://vocadb.net/Search?filter=@*&searchType=Artist). Perhaps more such specific website shortcuts could be implemented (e.g. p/ for piapro).
> Artist url parser for twitter

- Tests/Domain/Tags/TagTargetTypesTests.cs
- VocaDbModel/Domain/Tags/TagTargetTypes.cs
Prevents TagApiController.GetList from throwing 400 Bad Request.
> Add SongList to TagTargetTypes

- VocaDbWeb/Controllers/ReactController.cs
- VocaDbWeb/Scripts/App.tsx
- VocaDbWeb/Scripts/i18n.ts
- VocaDbWeb/Scripts/index.tsx
- VocaDbWeb/Startup.cs
- VocaDbWeb/Views/React/Index.cshtml
- VocaDbWeb/package-lock.json
- VocaDbWeb/package.json
- VocaDbWeb/tsconfig.json
- VocaDbWeb/webpack.mix.js
> Install packages for React, create ReactController

- VocaDbWeb/Scripts/Bootstrap/PageItem.tsx
- VocaDbWeb/Scripts/Components/Shared/Partials/EntryCountBox.tsx
- VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/EntryCount.tsx
- VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/ServerSidePaging.tsx
- VocaDbWeb/Scripts/Stores/ServerSidePagingStore.ts
- VocaDbWeb/package-lock.json
- VocaDbWeb/package.json
- VocaDbWeb/tsconfig.json
- VocaDbWeb/webpack.mix.js
> Convert ServerSidePaging to React

- VocaDbModel/Service/OtherService.cs
- VocaDbWeb/Views/Shared/Partials/Shared/_EventThumbs.cshtml
- VocaDbWeb/wwwroot/Content/Styles/base.less
Closes #849
I reduced the width of `.event-teaser` to keep events in one row. More events could cause bad line wrapping so everything beyond 4 needs a new row (Maybe implement that as an option with #95 ).
> Increase the amount of visible events

- VocaDbModel/Utils/AppConfig.cs
- VocaDbWeb/Models/Shared/GlobalValues.cs
- VocaDbWeb/Scripts/App.tsx
- VocaDbWeb/Scripts/Components/Admin/AdminIndex.tsx
- VocaDbWeb/Scripts/Components/Discussion/DiscussionFolders.tsx
- VocaDbWeb/Scripts/Components/Discussion/DiscussionIndex.tsx
- VocaDbWeb/Scripts/Components/Discussion/DiscussionRoutes.tsx
- VocaDbWeb/Scripts/Components/Discussion/DiscussionTopics.tsx
- VocaDbWeb/Scripts/Components/Discussion/Partials/ViewTopic.tsx
- VocaDbWeb/Scripts/Components/Search/SearchIndex.tsx
- VocaDbWeb/Scripts/Components/Shared/Layout.tsx
- VocaDbWeb/Scripts/Components/SongList/SongListFeatured.tsx
- VocaDbWeb/Scripts/Components/Stats/StatsIndex.tsx
- VocaDbWeb/Scripts/Components/User/UserIndex.tsx
- VocaDbWeb/Scripts/Components/usePageTracking.ts
- VocaDbWeb/Scripts/Components/useRouteParamsTracking.ts
- VocaDbWeb/Scripts/Components/useStoreWithPaging.ts
- VocaDbWeb/Scripts/Components/useStoreWithUpdateResults.ts
- VocaDbWeb/Scripts/Components/useVocaDbTitle.ts
- VocaDbWeb/Scripts/Shared/GlobalValues.ts
- VocaDbWeb/Views/React/Index.cshtml
- VocaDbWeb/package-lock.json
- VocaDbWeb/package.json
Closes #971.
Use the `usePageTracking` and `useRouteParamsTracking` hooks so that pageviews can be captured manually. Set `ready` to `false` while translations are not yet loaded. This prevents Google Analytics from using an incomplete page title (e.g. `Index.Discussions - Vocaloid Database`).
> Create usePageTracking and useRouteParamsTracking

- VocaDbWeb/Controllers/Api/SongListApiController.cs
Adds the `/api/songLists/{id:int}/details` endpoint, which will be used on the song list details page. We use the `/details` route for consistency with other endpoints (e.g. `/api/artists/{id:int}/details`, `/api/songs/{id:int}/details` and etc.).
> Add GetDetails to SongListApiController

- Tests/Helpers/XmlHelperTests.cs
After updating to .NET 6, the `System.Xml.Serialization.XmlSerializer.Serialize` method throws an `InvalidOperationException` if an invalid character is included. Were there any breaking changes in XmlSerializer, or is this something related to Unicode stuff? I couldn't find any documentation about that. Anyway, I don't see much benefit of allowing invalid characters.
> Fix XmlHelperTests

- VocaDbWeb/Models/Shared/GlobalValues.cs
- VocaDbWeb/Scripts/Shared/GlobalValues.ts
- VocaDbWeb/Startup.cs
- VocaDbWeb/Views/Shared/React/Index.cshtml
Part of #900.
Reference(s):
- [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0#generate-antiforgery-tokens-with-iantiforgery)
> Generate antiforgery tokens with IAntiforgery

- Tests/Domain/ReleaseEvents/ReleaseEventTypesTests.cs
- VocaDbModel/Domain/ReleaseEvents/EventCategory.cs
- VocaDbWeb/Scripts/Models/Events/EventCategory.ts
- VocaDbWeb/wwwroot/locales/en/VocaDb.Web.Resources.Domain.ReleaseEvents.json
- VocaDbWeb/wwwroot/locales/ja/VocaDb.Web.Resources.Domain.ReleaseEvents.json
> Added a new event enum value, "Festival"

- Tests/DataContracts/Users/UserDetailsForApiContractTests.cs
- Tests/Domain/Security/EntryPermissionManagerTests.cs
- VocaDbModel/DataContracts/Users/ServerOnlyUserContract.cs
- VocaDbModel/DataContracts/Users/UserDetailsForApiContract.cs
- VocaDbModel/Database/Queries/UserQueries.cs
- VocaDbModel/Domain/Security/EntryPermissionManager.cs
- VocaDbModel/Domain/Security/PermissionToken.cs
- VocaDbModel/Domain/Users/IUser.cs
- VocaDbModel/Domain/Users/User.cs
- VocaDbModel/Domain/Users/UserGroup.cs
- VocaDbWeb/Controllers/Api/UserApiController.cs
- VocaDbWeb/Controllers/UserController.cs
- VocaDbWeb/Scripts/DataContracts/User/UserDetailsContract.ts
- VocaDbWeb/Scripts/Models/LoginManager.ts
- VocaDbWeb/Scripts/Pages/User/UserOverview.tsx
Closes #1268.
Partially implements: #888.
This PR adds the following permissions: `ViewOldUsernames` and `ViewDisabledUser`. Mods+ have these permissions by default.
> Hide old usernames and disabled users

- VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs
Recent videos throw an error when trying to add them to entries, looks like int is not enough to store Bilibili user id anymore:
```
"owner": {
"mid": 3493103874869659,
"name": "もでお_MODEO",
"face": "https://i1.hdslb.com/bfs/face/c527a1dc30f8529dfa4443f984f845d11967684c.jpg"
}
```
([source](https://api.bilibili.com/x/web-interface/view?bvid=BV1AK411z7Vs))
> VideoServiceBilibili: user id type set to long

- VocaDbWeb/public/locales/ja/ViewRes.User.json
This is a pull request for minor Japanese improvements.
There was a slight difference in Japanese on some pages (login page for artists).
- 'ログオン' -> 'ログイン'
Current Japanese web site applications do not display 'ログオン'.
Thank you. 😊
> Minor improvements in Japanese

- VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs
I am not familiar with C# so this code needs a good review first.
https://vocadb.net/api/pvs and https://vocadb.net/api/songs/findDuplicate would return "Sorry, an unhandled error occurred :(" instead of expected JSON data.
The log was like this:
```
[.NET ThreadPool Worker] INFO Loading Bilibili URL http://bilibili.com/video/av575832 
[.NET ThreadPool Worker] ERROR An unhandled exception has occurred while executing the request. - System.NullReferenceException Object reference not set to an instance of an object. Void MoveNext()    at VocaDb.Model.Service.VideoServices.VideoServiceBilibili.ParseByUrlAsync(String url, Boolean getTitle) in /tmp/vocadb-dev/git/vocadb/VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs:line 53
at …
```
> bilibili, fix unhandled exception for unviewable videos

- VocaDbWeb/Controllers/Api/SongApiController.cs
- VocaDbWeb/Scripts/Pages/Artist/ArtistBasicInfo.tsx
- VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx
> Final language field fixes

- VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/DropdownList.tsx
Quick fix, which changes the default sorting order for the extended languages dropdown to alphabetically.
> fix: Sort languages by english name

- VocaDbModel/Database/Queries/ActivityEntryQueries.cs
- VocaDbModel/Service/ArtistService.cs
- VocaDbModel/Service/OtherService.cs
- VocaDbModel/Service/Queries/ActivityEntryQueries.cs
- VocaDbModel/Service/ServiceBase.cs
- VocaDbModel/Service/SongService.cs
Currently `/api/activityEntries` automatically deduplicates activity entries and doesn't contain deletion events. This is somewhat unexpected for some api users who expect this endpoint to be a stream of all database updates. The frontpage activity entry section is separate from this endpoint and will continue to function normally.
> refactor: Update /api/activityEntries

- VocaDbModel/DataContracts/Albums/AlbumForApiContract.cs
- VocaDbModel/DataContracts/Albums/AlbumReleaseContract.cs
- VocaDbModel/DataContracts/Albums/ArchivedAlbumReleaseContract.cs
- VocaDbModel/Database/Queries/AlbumQueries.cs
- VocaDbModel/Database/Queries/EventQueries.cs
- VocaDbModel/Database/Queries/SongQueries.cs
- VocaDbModel/Domain/Albums/AlbumRelease.cs
- VocaDbModel/Mapping/Albums/AlbumMap.cs
- VocaDbWeb/Scripts/Bootstrap/AbstractNav.tsx
- VocaDbWeb/Scripts/Bootstrap/safeFindDOMNode.ts
- VocaDbWeb/Scripts/Components/KnockoutExtensions/EntryToolTip.tsx
- VocaDbWeb/Scripts/Components/Shared/Partials/Event/EventLink.tsx
- VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/ReleaseEventsEditView.tsx
- VocaDbWeb/Scripts/DataContracts/Album/AlbumDetailsForApi.ts
- VocaDbWeb/Scripts/DataContracts/Album/AlbumReleaseContract.ts
- VocaDbWeb/Scripts/Pages/Album/AlbumBasicInfo.tsx
- VocaDbWeb/Scripts/Pages/Album/AlbumEdit.tsx
- VocaDbWeb/Scripts/Pages/Song/SongBasicInfo.tsx
- VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx
- VocaDbWeb/Scripts/Stores/Album/AlbumEditStore.ts
#1544 implemented multiple release events for songs. This PR adds the functionality to albums.
TODO
> feat: Allow multiple release events for albums

- VocaDbWeb/Scripts/DataContracts/Album/AlbumContract.ts
- VocaDbWeb/Scripts/Pages/Search/Partials/AlbumSearchList.tsx
- VocaDbWeb/Scripts/Stores/Album/AlbumEditStore.ts
- VocaDbWeb/Scripts/Stores/Song/SongEditStore.ts
> fix: Smaller release event fixes

- VocaDbModel/Database/Queries/EntryQueries.cs
Fixes a bug where all tags were returned if a user had selected a tag filter ([example](https://vocadb.net/Search?tagId=4997)).
> fix: Remove tags from "anything" search results if a tag filter is used

- VocaDbWeb/Scripts/Components/extendedUserLanguageCultures.ts
- VocaDbWeb/Scripts/Components/userLanguageCultureFamilies.ts
This PR includes the following changes to the language list:
- Added Serbian
- Added Sambahsa
- Added Hokkien, Teochew and Hainanese (preserved Southern Min)
- Added Zhuang, Tangut, Middle Korean, Nuosu, Tujia, Manchu, Hmong, Kam, Pu-Xian, Hani, Qiang, Bunun and Uyghur
- Added Hokkien, Teochew, Hainanese and Pu-Xian to the Chinese language family
- Created a Korean language family and added Middle Korean
The current language list can be found in the [online spreadsheet](https://docs.google.com/spreadsheets/d/1DQPeAn3echjZMgJBdXpFkeEsNQ6nN0csehiCLy_ApZM/edit#gid=0).
> chores: Update language options

- VocaDbWeb/Controllers/Api/AlbumApiController.cs
- VocaDbWeb/Controllers/Api/ArtistApiController.cs
- VocaDbWeb/Controllers/Api/ReleaseEventApiController.cs
- VocaDbWeb/Controllers/Api/SongApiController.cs
- VocaDbWeb/Controllers/Api/TagApiController.cs
- VocaDbWeb/Helpers/EditRateLimitService.cs
- VocaDbWeb/Startup.cs
The new EditRateLimitService maintains a rolling window of 1 hour. The following limits apply
- 100 edit requests per hour (regular users)
- 500 edit requests per hour (trusted users)
- unlimited edit requests per hour (moderator & admin)
> feat: Implement edit rate limit

- VocaDbWeb/Scripts/Components/extendedUserLanguageCultures.ts
- Amis is a indigenous language in Taiwan.
- Hausa currently uses the Latin script.
> chores: Add Amis; change native sc. for Hausa

- VocaDbModel/Domain/Songs/LyricsForSong.cs
- VocaDbModel/Domain/Users/UserGroup.cs
Fixes a bug where lyrics are always included in `changedFields`.
> fix: Correctly compare culture codes for lyrics

- VocaDb.Migrations/Migrations.cs
Closes #1722. This also has the side effect of migrating the remaining NND http URLs to https.
> fix: Migrate to the new NND thumbnail URLs

- VocaDbWeb/Scripts/Pages/Tag/TagEdit.tsx
Removes the empty "Voice Synthesizer" section in the new tag edit menu on TouhouDB.
> fix: Filter out tag target types with no subtypes

- VocaDbModel/Service/Helpers/ArtistExternalUrlParser.cs
Closes #1805. We're mapping searches for x.com to twitter.com for now.
#1765 will normalize x.com to twitter.com URLs while editing external links in the future.
> feat: Support x.com in ArtistExternalUrlParser.cs

- VocaDbModel/Domain/Constants.cs
- VocaDbWeb/Controllers/Api/AlbumApiController.cs
- VocaDbWeb/Controllers/Api/ArtistApiController.cs
- VocaDbWeb/Controllers/Api/SongApiController.cs
- VocaDbWeb/Program.cs
- VocaDbWeb/Startup.cs
Closes #1596 and adds a 40 req/minute sliding window rate limit and a max. 4 concurrent requests limit for /details endpoints.
> feat: /Details rate limiting

- VocaDbWeb/Scripts/Components/KnockoutExtensions/EntryToolTip.tsx
Tooltip currently does not update value (e.g. artist) is currently already in state. This can effectively be solved by no longer immediately returning when the value is known, but also comparing its id against the current supplied id.
Closes https://github.com/VocaDB/vocadb/issues/1378
> Bugfix 1378 Tooltip incorrect display.

- VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts
- lyricstranslate - also often records translyrics
- telegram - frequently used in russia
- korean wikipedia - korean wikipedia :kr: :+1: 
- boosty: russian equivalent of patreon/ko-fi? also frequently seen
- fandub.wiki: russian youtaite wiki
> chores: Add new linkmatchers
