VocaDbModel/Resources/AlbumValidationErrors.ja.resx, VocaDbModel/Resources/Albums/DiscTypeNames.ja.resx, VocaDbModel/Resources/ArtistValidationErrors.ja.resx, VocaDbModel/Resources/ExtSites.ja.resx, VocaDbModel/Resources/SongValidationErrors.ja.resx, VocaDbModel/Resources/Songs/SongTypeNames.ja.resx, VocaDbModel/Resources/Views/AlbumRes.ja.resx, VocaDbModel/Resources/Views/SongRes.ja.resx
Can you add these to the project file? I couldn't figure out to do this in VB. Thanks. 
VocaDbModel/Resources/AlbumValidationErrors.ja.resx
VocaDbModel/Resources/ArtistValidationErrors.ja.resx
VocaDbModel/Resources/ExtSites.ja.resx
VocaDbModel/Resources/SongValidationErrors.ja.resx
VocaDbModel/Resources/Views/AlbumRes.ja.resx
Also, I'm not sure if I was supposed to  "Merge remote-tracking branch 'upstream/master" to sync with the upstream repo before the pull request.
=> Add ja translations in VocaDB.Model

VocaDbWeb/App_GlobalResources/EntryReportTypeNames.ja.resx, VocaDbWeb/Resources/Views/User/DetailsStrings.ja.resx, VocaDbWeb/Resources/Views/User/RequestVerificationStrings.ja.resx
Please add the new file to the project.
=> Verification page (Jp)

VocaDbModel/Resources/Songs/SongTypeNames.ja.resx, VocaDbWeb/App_GlobalResources/AlbumArchiveReasonNames.ja.resx, VocaDbWeb/App_GlobalResources/ArtistArchiveReasonNames.ja.resx, VocaDbWeb/App_GlobalResources/SongArchiveReasonNames.ja.resx, VocaDbWeb/Resources/Views/Album/EditStrings.ja.resx, VocaDbWeb/Resources/Views/Song/EditStrings.ja.resx
`VocaDbWeb/Resources/Views/Album/EditStrings.ja.resx` is a new file so please add it to the project. Thanks.
=> Add Resource/Views/Album/EditStrings.ja.resx, tweak few jp translations.

VocaDbWeb/Resources/Views/Discussion/IndexStrings.ja.resx
Please add the project file thingy.
=> Add jp discussion strings

VocaDbModel/Resources/AlbumValidationErrors.es.resx, VocaDbWeb/App_GlobalResources/ArtistEditableFieldNames.pt.resx, VocaDbWeb/Resources/Ajax/EntryIndexStrings.pt.resx, VocaDbWeb/Resources/Controllers/TagControllerStrings.pt.resx, VocaDbWeb/Resources/Views/Artist/EditStrings.pt.resx, VocaDbWeb/Resources/Views/Event/EventsBySeriesStrings.pt.resx, VocaDbWeb/Resources/Views/Shared/SharedStrings.pt.resx, VocaDbWeb/Resources/Views/User/LoginStrings.pt.resx, VocaDbWeb/Resources/Views/User/MySettingsStrings.pt.resx
=> Portuguese fixes

VocaDbWeb/Resources/Views/User/AlbumCollectionStrings.de.resx
Added German translations proposed by Shnyx
=> Update to AlbumCollectionStrings.de.resx

VocaDbModel/Resources/ArtistTypeNames.de.resx, VocaDbWeb/App_GlobalResources/SongEditableFieldNames.de.resx, VocaDbWeb/Resources/Helpers/ActivityFeedHelperStrings.de.resx, VocaDbWeb/Resources/Views/ActivityEntry/IndexStrings.de.resx, VocaDbWeb/Resources/Views/Album/DetailsStrings.de.resx, VocaDbWeb/Resources/Views/Album/EditStrings.de.resx, VocaDbWeb/Resources/Views/Artist/DetailsStrings.de.resx, VocaDbWeb/Resources/Views/Artist/EditStrings.de.resx, VocaDbWeb/Resources/Views/Discussion/IndexStrings.de.resx, VocaDbWeb/Resources/Views/Event/DetailsStrings.de.resx, VocaDbWeb/Resources/Views/Home/IndexStrings.de.resx, VocaDbWeb/Resources/Views/Search/IndexStrings.de.resx, VocaDbWeb/Resources/Views/Shared/EntryDetailsStrings.de.resx, VocaDbWeb/Resources/Views/Shared/EntryEditStrings.de.resx, VocaDbWeb/Resources/Views/Shared/_LayoutStrings.de.resx, VocaDbWeb/Resources/Views/Song/DetailsStrings.de.resx, VocaDbWeb/Resources/Views/Song/EditStrings.de.resx, VocaDbWeb/Resources/Views/Song/RankingsStrings.de.resx, VocaDbWeb/Resources/Views/SongList/EditStrings.de.resx, VocaDbWeb/Resources/Views/SongList/FeaturedStrings.de.resx, VocaDbWeb/Resources/Views/SongList/SongListSortRuleNames.de.resx, VocaDbWeb/Resources/Views/User/AlbumCollectionStrings.de.resx, VocaDbWeb/Resources/Views/User/DetailsStrings.de.resx, VocaDbWeb/Resources/Views/User/MessagesStrings.de.resx, VocaDbWeb/Resources/Views/User/MySettingsStrings.de.resx, VocaDbWeb/Resources/Views/User/RatedSongsStrings.de.resx
Hopefully I'm doing this right.
=> Shnyx translations

VocaDbWeb/Resources/Domain/EntryTypeNames.ja.resx, VocaDbWeb/Resources/Views/User/DetailsStrings.de.resx, VocaDbWeb/Resources/Views/User/DetailsStrings.ja.resx
German:
Had missed a comment -> Kommentare
Japanese
Event/events -> イベント
=> +Translations

VocaDbWeb/Resources/Views/Shared/EntryMergeStrings.resx
Is it okay for me to adjust or correct some grammar?
If so...
=> Update to EntryMergeStrings.resx

VocaDbWeb/Content/Styles/ExtLinks.css
Made multiple branches (still a little new to this--now I've realized I can just do it all in one) so now I'm merging them together.
=> Merging own branches

VocaDbWeb/Views/Help/Index.cshtml, VocaDbWeb/Views/Help/Index.ja.cshtml, VocaDbWeb/Views/Help/Index.zh-Hans.cshtml
I hope it's okay I did more proofreading. I removed the Delicious Cake project link since it wasn't active anymore.
I commented out the vocaloidotaku.net reference, since that's not active either, but the location is retained in case we'd like to put something else there.
=> Proofreading

VocaDbModel/Resources/Albums/DiscTypeNames.ja.resx, VocaDbWeb/App_GlobalResources/ReleaseEventEditableFieldNames.ja.resx, VocaDbWeb/Resources/Views/Artist/EditStrings.ja.resx, VocaDbWeb/Resources/Views/Search/IndexStrings.ja.resx, VocaDbWeb/Resources/Views/Shared/_LayoutStrings.ja.resx, VocaDbWeb/Resources/Views/Song/DetailsStrings.ja.resx, VocaDbWeb/Resources/Views/Tag/DetailsStrings.ja.resx, VocaDbWeb/Resources/Views/User/MySettingsStrings.ja.resx
I was going to wait for DD to get back to me on one of the translations (for "Artist's Personal Description"), but I think we can merge these for now. I can add it later.
DD, if you happen to see this, feel free to let me know what you think would be best for that, and I can add it. [The discussion is here, for reference](https://vocadb.net/discussion/topics/6).
I did some rearranging in some files, so if anything is syntactically incorrect, it'd be from that. (The reason for rearranging was to better match the order of the English version.) Let me know if there's an error and I can fix it.
=> Japanese interface translations

VocaDbModel/Helpers/CollectionHelper.cs
The SyncWithContent method can be simplified by using the Sync method.
=> Clean up CollectionHelper

VocaDbModel/Database/Queries/UserQueries.cs, VocaDbModel/Service/QueryableExtenders/ArtistLinkQueryableExtender.cs, VocaDbModel/Service/Search/User/FollowedArtistQueryParams.cs, VocaDbWeb/Controllers/Api/UserApiController.cs, VocaDbWeb/Scripts/Repositories/UserRepository.ts, VocaDbWeb/Scripts/ViewModels/User/FollowedArtistsViewModel.ts, VocaDbWeb/Views/User/Details.cshtml, VocaDbWeb/Views/User/Partials/_FollowedArtists.cshtml
=> Followed artists tab on user page: filter by tag

VocaDbModel/Database/Queries/UserQueries.cs, VocaDbModel/Domain/Security/PermissionToken.cs, VocaDbModel/Domain/Tags/Tag.cs, VocaDbModel/Domain/Users/UserGroup.cs, VocaDbModel/Domain/Users/UserReport.cs, VocaDbWeb/Controllers/Api/UserApiController.cs, VocaDbWeb/Resources/Domain/EntryReportTypeNames.designer.cs, VocaDbWeb/Resources/Domain/EntryReportTypeNames.resx, VocaDbWeb/Resources/Views/User/DetailsStrings.Designer.cs, VocaDbWeb/Resources/Views/User/DetailsStrings.resx, VocaDbWeb/Scripts/User/Details.ts, VocaDbWeb/Scripts/ViewModels/User/UserDetailsViewModel.ts, VocaDbWeb/Views/User/Details.cshtml
#527
TODO: make notes mandatory (currently silently ignores). Maybe change to ReportEntryViewModel.
TODO: unit tests.
TODO: prevent multiple open reports by the same user.
=> Report users for spamming

Tests/Web/Controllers/DataAccess/UserQueriesTests.cs, VocaDbModel/Database/Queries/UserQueries.cs, VocaDbModel/Service/Security/StopForumSpam/SFSResponseContract.cs
#529 
Create report for uncertain spammer, when match is found in SFS database.
=> 529 report uncertain

Tests/Service/Queries/TagUsageQueriesTests.cs, VocaDbModel/Domain/Albums/Album.cs, VocaDbModel/Domain/Artists/Artist.cs, VocaDbModel/Domain/ReleaseEvents/ReleaseEvent.cs, VocaDbModel/Domain/ReleaseEvents/ReleaseEventSeries.cs, VocaDbModel/Domain/Songs/Song.cs, VocaDbModel/Domain/Songs/SongList.cs, VocaDbModel/Domain/Tags/IEntryWithTags.cs, VocaDbModel/Service/Queries/TagUsageQueries.cs
#559 Although I'm not sure if this is the right way to fix this, it seems to work fine.
=> Fix TagUsageQueries

VocaDbWeb/Scripts/Venue/Edit.js
=> Add Venue/Edit.js

VocaDbModel/Database/Queries/UserQueries.cs, VocaDbModel/Helpers/MailAddressNormalizer.cs, VocaDbWeb/Controllers/UserController.cs, VocaDbWeb/Models/UserModels.cs, VocaDbWeb/Views/User/Edit.cshtml
=> Catch exceptions

VocaDbModel/DataContracts/Venues/VenueForApiContract.cs
#657 The venues are sorted by date in *ascending* order.
=> Sort events on venue page by date

VocaDbModel/Database/Queries/TagQueries.cs
=> Catch GenericADOException

VocaDbModel/DataContracts/Songs/SongDetailsContract.cs, VocaDbWeb/Views/Song/Details.cshtml
=> Render lyrics on the server side

VocaDbWeb.Core/App.config
=> Copy `Web.config` from VocaDbWeb to VocaDbWeb.Core

VocaDbModel/Service/SongImport/NicoNicoMyListParser.cs
=> Fix NicoNicoMyListParser

VocaDbModel/DataContracts/Users/ArtistForUserForApiContract.cs, VocaDbModel/Database/Queries/UserQueries.cs, VocaDbWeb/Controllers/Api/UserApiController.cs
=> Implement API for getting followed artist

VocaDbWeb.Core/Program.cs, VocaDbWeb.Core/VocaDbWeb.Core.csproj, VocaDbWeb.Core/nlog.config
=> Install NLog.Web.AspNetCore

VocaDbModel/Domain/Globalization/RegionCollection.cs, VocaDbWeb.Core/Views/Venue/Edit.cshtml, VocaDbWeb/Views/Venue/Edit.cshtml
=> Fix RegionCollection

VocaDbModel/DataContracts/Users/AlbumForUserForApiContract.cs, VocaDbModel/Database/Queries/UserQueries.cs, VocaDbWeb/Controllers/Api/UserApiController.cs
=> Implement API for getting album collection status

VocaDbWeb.Core/Views/Song/Details.cshtml
=> Fix Song/Details.cshtml

VocaDbWeb.Core/Controllers/UserController.cs, VocaDbWeb.Core/Startup.cs, VocaDbWeb.Core/VocaDbWeb.Core.csproj
=> Implement sign in with twitter

VocaDbWeb.Core/Controllers/StatsController.cs, VocaDbWeb.Core/Startup.cs
=> Replace GetCachedReport and SaveCachedReport with GetOrInsert

VocaDbWeb.Core/Code/Feeds/FeedResult.cs, VocaDbWeb.Core/Code/Feeds/SongFeedFactory.cs, VocaDbWeb.Core/Controllers/SongController.cs, VocaDbWeb.Core/Helpers/ViewRenderService.cs, VocaDbWeb.Core/VocaDbWeb.Core.csproj
=> Implement Feed and LatestVideos

VocaDbWeb/wwwroot/Scripts/Repositories/UserRepository.ts
=> Fix UserRepository.updateUserSetting

VocaDbWeb/Views/Shared/Partials/Artist/_ArtistList.cshtml
=> Remove extra space between artists

VocaDbWeb/Controllers/TagController.cs
=> Replace ResponseCacheLocation.Any with ResponseCacheLocation.Client

VocaDbWeb/Views/Admin/ViewAuditLog.cshtml
=> Fix ViewAuditLog

VocaDbWeb/Controllers/Api/UserApiController.cs
=> Fix mass notification deletion

VocaDbWeb/Controllers/EventController.cs, VocaDbWeb/Controllers/ExtController.cs, VocaDbWeb/Controllers/StatsController.cs, VocaDbWeb/Controllers/TagController.cs, VocaDbWeb/Controllers/UserController.cs
=> Specify VaryByQueryKeys

VocaDbWeb/Controllers/AlbumController.cs, VocaDbWeb/Controllers/ArtistController.cs, VocaDbWeb/Controllers/ControllerBase.cs, VocaDbWeb/Views/Artist/Edit.cshtml
=> Fix AlbumController.Edit and ArtistController.Edit

VocaDbWeb/Controllers/Api/AlbumApiController.cs, VocaDbWeb/Controllers/Api/ArtistApiController.cs, VocaDbWeb/Controllers/Api/SongApiController.cs, VocaDbWeb/Controllers/Api/SongListApiController.cs, VocaDbWeb/Controllers/Api/UserApiController.cs, VocaDbWeb/Models/Shared/AdvancedSearchFilterParams.cs
Fixes #793.
Reference(s):
- [c# - How do I reproduce the [FromUri] behavior for complex parameters in .NET Core 2.1 - Stack Overflow](https://stackoverflow.com/questions/51423649/how-do-i-reproduce-the-fromuri-behavior-for-complex-parameters-in-net-core-2/51426635#51426635)
=> Fix advanced search filters

VocaDbWeb/Startup.cs
Fixes VocaDB/roadkill-vocadb-auth#2.
=> Specify Cookie.Domain

VocaDbWeb/wwwroot/Content/Site.css, VocaDbWeb/wwwroot/Content/Styles/ExtLinks.less
=> Spotify and CDJapan Icons not showing on entries

VocaDbModel/Database/Queries/SongQueries.cs, VocaDbWeb/wwwroot/Scripts/ViewModels/SongCreateViewModel.ts
=> Filter out already listed songs in Duplications warning #496

VocaDbWeb/wwwroot/Content/Styles/Overrides.less
Fixes #425. Maybe needs to be tested on the beta site to ensure that there are no unwanted side effects
=> "Song ratings" pop-up goes out of view when dragging over its title #425

VocaDbWeb/Startup.cs, VocaDbWeb/VocaDbWeb.csproj
=> Install Swashbuckle.AspNetCore.Newtonsoft

.mailmap
Added git mailmap to get rid of some email aliases. Although I'm not sure if Github supports it, at least local git history will be more clear.
=> added mailmap

VocaDbModel/Resources/ArtistTypeNames.ja.resx
Translation from Hikaru Soeda (https://discord.com/channels/309072240639737866/808128811056889886/828271413483667477)
=> Add translation for Cover artist

VocaDbModel/Resources/ArtistCategoriesNames.resx, VocaDbModel/VocaDb.Model.csproj, VocaDbWeb/Helpers/Translate.cs, VocaDbWeb/Views/Artist/Create.cshtml, VocaDbWeb/Views/Artist/Edit.cshtml, VocaDbWeb/Views/Shared/Partials/Artist/_ArtistTypesDropdownKnockout.cshtml
=> Group artist types by category

VocaDbModel/DataContracts/Api/EntryForApiContract.cs
=> Add default constructor to EntryForApiContract

VocaDbModel/Resources/Views/SongRes.resx, VocaDbWeb/Views/Shared/KnockoutPartials/_DuplicateEntriesMessage.cshtml, VocaDbWeb/Views/Song/Create.cshtml, VocaDbWeb/wwwroot/Content/Styles/Overrides.less
Fixes various bugs:
- Decrease fieldset margin
- Change "Vocaloid" to "Voice synthesizer" in SongRes.resx
- Move alerts into one column
=> Alerts in one column

VocaDbWeb/Views/Song/Partials/_LyricsForSongEdit.cshtml, VocaDbWeb/wwwroot/Scripts/ViewModels/Song/LyricsForSongEditViewModel.ts
=> Autofill label from URL when adding lyrics to a song

VocaDbWeb/Code/Web/AspNetCoreHttpPostedFile.cs
Fixes #868. `FileStream` needs to be disposed.
=> Dispose FileStream

VocaDbWeb/Startup.cs
=> Catch exceptions, redirect to ErrorController

VocaDbWeb/Scripts/Components/Shared/Partials/Artist/ArtistTypeLabel.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Song/SongTypeLabel.tsx
=> Convert ArtistTypeLabel and SongTypeLabel to React

VocaDbWeb/Models/Shared/GlobalValues.cs, VocaDbWeb/Scripts/App.tsx, VocaDbWeb/Scripts/Bootstrap/Alert.tsx, VocaDbWeb/Scripts/Bootstrap/CloseButton.tsx, VocaDbWeb/Scripts/Components/Error/ErrorNotFound.tsx, VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx, VocaDbWeb/Scripts/Components/Shared/Layout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Footer.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/LeftMenu.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/MainNavigationItems.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/PatreonLink.tsx, VocaDbWeb/Scripts/Models/LoginManager.ts, VocaDbWeb/Scripts/Shared/GlobalValues.ts
=> Convert Layout to React

VocaDbWeb/Scripts/Components/Shared/Partials/User/IconAndLinkKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/User/IconAndNameKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/User/IconAndNameLinkKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/User/IconNameAndTypeLinkKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/User/ProfileIconKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/User/ProfileIconKnockout_ImageSize.tsx, VocaDbWeb/Scripts/DataContracts/User/UserApiContract.ts, VocaDbWeb/Scripts/Models/Images/ImageSize.ts, VocaDbWeb/Scripts/Models/Users/UserGroup.ts, VocaDbWeb/Scripts/Shared/EntryUrlMapper.ts
=> Convert ProfileIconKnockout to React

VocaDbModel/DataContracts/Users/SanitizedUserWithPermissionsContract.cs, VocaDbWeb/Scripts/App.tsx, VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx, VocaDbWeb/Scripts/DataContracts/User/UserWithPermissionsContract.ts, VocaDbWeb/Scripts/JQueryUI/Autocomplete.tsx, VocaDbWeb/Scripts/Models/LoginManager.ts, VocaDbWeb/Scripts/Stores/TopBarStore.ts, VocaDbWeb/Scripts/Tests/Models/LoginManager.test.ts
Depends on #908.
Depends on #914.
=> Implement GlobalSearchBox

VocaDbWeb/Scripts/Components/KnockoutExtensions/Markdown.tsx, VocaDbWeb/Scripts/Components/KnockoutExtensions/MomentJsTimeAgo.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/CommentBodyEditableKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/CommentBodyKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/CommentKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/CreateComment.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/EditableComments.tsx, VocaDbWeb/Scripts/DataContracts/Discussion/DiscussionFolderContract.ts, VocaDbWeb/Scripts/DataContracts/Discussion/DiscussionTopicContract.ts, VocaDbWeb/Scripts/Models/LoginManager.ts, VocaDbWeb/package-lock.json, VocaDbWeb/package.json
=> Convert comment partial views to React

VocaDbWeb/Controllers/SongListController.cs, VocaDbWeb/Scripts/App.tsx, VocaDbWeb/Scripts/Components/Shared/Layout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/MainNavigationItems.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Song/SongListsKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/SongListsFilters.tsx, VocaDbWeb/Scripts/Components/SongList/SongListFeatured.tsx, VocaDbWeb/Scripts/Components/SongList/SongListRoutes.tsx, VocaDbWeb/Scripts/DataContracts/Song/SongListContract.ts, VocaDbWeb/Scripts/Models/LoginManager.ts
=> Convert songlist featured to React

VocaDbWeb/Scripts/Components/Search/Partials/AlbumSearchList.tsx, VocaDbWeb/Scripts/Components/Search/Partials/AnythingSearchList.tsx, VocaDbWeb/Scripts/Components/Search/Partials/ArtistSearchList.tsx, VocaDbWeb/Scripts/Components/Search/Partials/EventSearchList.tsx, VocaDbWeb/Scripts/Components/Search/Partials/SongSearchList.tsx, VocaDbWeb/Scripts/Components/Search/Partials/TagSearchList.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/LeftMenu.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Shared/Stars.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Shared/StarsMeta.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Song/SongListsKnockout.tsx, VocaDbWeb/Scripts/Components/SongList/SongListFeatured.tsx, VocaDbWeb/Scripts/Components/Stats/StatsIndex.tsx, VocaDbWeb/Scripts/Components/User/Partials/ListUsers.tsx, VocaDbWeb/Scripts/DataContracts/Album/AlbumContract.ts, VocaDbWeb/Scripts/DataContracts/Artist/ArtistContract.ts, VocaDbWeb/Scripts/DataContracts/EntryContract.ts, VocaDbWeb/Scripts/DataContracts/ReleaseEvents/EventSeriesContract.ts, VocaDbWeb/Scripts/DataContracts/ReleaseEvents/ReleaseEventContract.ts, VocaDbWeb/Scripts/Stores/Search/SearchStore.ts
=> Convert search lists to React

VocaDbWeb/Scripts/Components/KnockoutExtensions/ArtistAutoComplete.tsx, VocaDbWeb/Scripts/Components/KnockoutExtensions/AutoCompleteParams.ts, VocaDbWeb/Scripts/Components/KnockoutExtensions/ReleaseEventAutoComplete.tsx, VocaDbWeb/Scripts/Components/KnockoutExtensions/SongAutoComplete.tsx, VocaDbWeb/Scripts/Components/KnockoutExtensions/TagCategoryAutoComplete.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/CommentBodyEditableKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/BasicEntryLinkLockingAutoComplete.tsx
=> Convert Knockout extensions to React

VocaDbWeb/Models/Shared/GlobalValues.cs, VocaDbWeb/Scripts/Components/Search/Partials/AlbumSearchOptions.tsx, VocaDbWeb/Scripts/Components/Search/Partials/ArtistSearchOptions.tsx, VocaDbWeb/Scripts/Components/Search/Partials/EventSearchOptions.tsx, VocaDbWeb/Scripts/Components/Search/Partials/SongBpmFilter.tsx, VocaDbWeb/Scripts/Components/Search/Partials/SongLengthFilter.tsx, VocaDbWeb/Scripts/Components/Search/Partials/SongSearchOptions.tsx, VocaDbWeb/Scripts/Components/Search/Partials/TagSearchOptions.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Album/DiscTypesDropdownKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Artist/ArtistTypesDropdownKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/ArtistFilters.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/DropdownList.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/LockingAutoComplete.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/ReleaseEventLockingAutoComplete.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/SongLockingAutoComplete.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/TagCategoryLockingAutoComplete.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Song/ArtistParticipationStatusOptionsKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Song/SongTypesDropdownKnockout.tsx, VocaDbWeb/Scripts/JQueryUI/JQueryUIDatepicker.tsx, VocaDbWeb/Scripts/Models/Artists/ArtistCategories.ts, VocaDbWeb/Scripts/Shared/GlobalValues.ts
=> Convert search options to React

VocaDbModel/Service/VideoServices/VideoServiceSoundCloud.cs, VocaDbModel/Utils/AppConfig.cs
=> Update the integration with SoundCloud API

VocaDbModel/Domain/Caching/ObjectCacheExtensions.cs, VocaDbModel/Helpers/HtmlRequestHelper.cs, VocaDbModel/Helpers/JsonRequest.cs, VocaDbModel/Service/VideoServices/VideoParseException.cs, VocaDbModel/Service/VideoServices/VideoServiceSoundCloud.cs
=> Cache token for one hour

VocaDbWeb/Scripts/ViewModels/Artist/ArtistEditViewModel.ts
Fixes #1033 
p.s. the ArtistType "Band", "Character" was not for vocadb (only for utaitedb/touhoudb), was it?
=> fix #1033: base voicebank field should enlist synthv voicebanks

Tests/GitHubIssues/Issue1062/ArtistQueriesTests.cs, Tests/GitHubIssues/Issue1062/SongQueriesTests.cs, Tests/Web/Controllers/DataAccess/ArtistQueriesTests.cs, Tests/Web/Controllers/DataAccess/SongQueriesTests.cs, VocaDbModel/Database/Queries/AlbumQueries.cs, VocaDbModel/Database/Queries/ArtistQueries.cs, VocaDbModel/Database/Queries/EventQueries.cs, VocaDbModel/Database/Queries/SongQueries.cs, VocaDbModel/Database/Queries/TagQueries.cs, VocaDbModel/Database/Queries/VenueQueries.cs, VocaDbModel/Domain/Songs/SongReport.cs, VocaDbModel/Service/Queries/EntryReportQueries.cs, VocaDbWeb.Resources/Resources/Ajax/SharedStrings.resx, VocaDbWeb/Controllers/AlbumController.cs, VocaDbWeb/Controllers/Api/ReleaseEventApiController.cs, VocaDbWeb/Controllers/Api/TagApiController.cs, VocaDbWeb/Controllers/Api/VenueApiController.cs, VocaDbWeb/Controllers/ArtistController.cs, VocaDbWeb/Controllers/SongController.cs, VocaDbWeb/Scripts/Components/Shared/Partials/EntryDetails/ReportEntryPopupKnockout.tsx, VocaDbWeb/Scripts/Components/ui.tsx, VocaDbWeb/Scripts/Models/Songs/SongReportType.ts, VocaDbWeb/wwwroot/locales/en/AjaxRes.json
=> Feat/1062 required notes field for broken PV

VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx, VocaDbWeb/Scripts/Components/Shared/ShowRandomPageButton.tsx, VocaDbWeb/wwwroot/Content/Styles/base.less
=> Add random page button to global search box

VocaDbWeb/Scripts/Components/Shared/Partials/PlayList.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Song/PVPreviewKnockout.tsx, VocaDbWeb/Scripts/Components/Song/SongDetails.tsx, VocaDbWeb/Scripts/DataContracts/Song/SongWithPVPlayerAndVoteContract.ts, VocaDbWeb/Scripts/Stores/PVs/PVPlayerStore.ts, VocaDbWeb/Scripts/Stores/Song/SongDetailsStore.ts, VocaDbWeb/Scripts/Stores/Song/SongWithPreviewStore.ts
This PR lets PV players be rendered on the client side rather than the server.
=> Use EmbedPV everywhere

.gitignore, Tests/Service/VideoServices/NicoLogHelperTests.cs, VocaDbModel/Database/Queries/SongQueries.cs, VocaDbModel/Domain/PVs/PV.cs, VocaDbModel/Service/VideoServices/IVideoService.cs, VocaDbModel/Service/VideoServices/NicoLogParser.cs, VocaDbModel/Service/VideoServices/VideoService.cs, VocaDbModel/Service/VideoServices/VideoServiceHelper.cs
To fill metadata for songs that have been deleted from Nicovideo
=> added parser for nicolog

VocaDbModel/Database/Queries/EventQueries.cs
=> Fix creating events with pv links

VocaDbModel/Database/Queries/CommentQueries.cs, VocaDbWeb/Controllers/Api/CommentApiController.cs, VocaDbWeb/Controllers/CommentController.cs, VocaDbWeb/Scripts/AppRoutes.tsx, VocaDbWeb/Scripts/Components/ActivityEntry/ActivityEntryIndex.tsx, VocaDbWeb/Scripts/Components/Admin/AdminIndex.tsx, VocaDbWeb/Scripts/Components/Comment/CommentIndex.tsx, VocaDbWeb/Scripts/Components/Comment/CommentRoutes.tsx, VocaDbWeb/Scripts/Components/Home/HomeIndex.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/DropdownList.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/UserLockingAutoComplete.tsx, VocaDbWeb/Scripts/Components/User/Partials/ListUsers.tsx, VocaDbWeb/Scripts/Components/User/UserOverview.tsx, VocaDbWeb/Scripts/Stores/ActivityEntry/ActivityEntryListStore.ts, VocaDbWeb/Scripts/Stores/Comment/CommentListRouteParams.schema.json, VocaDbWeb/Scripts/Stores/Comment/CommentListStore.ts
=> Convert comment index to React

VocaDbModel/Service/Search/SongSearch/SongSearch.cs, VocaDbWeb/Controllers/Api/SongApiController.cs
=> Prefer original song entries

VocaDbWeb/Scripts/Components/Album/AlbumCreate.tsx, VocaDbWeb/Scripts/Components/Artist/ArtistCreate.tsx, VocaDbWeb/Scripts/Components/Shared/KnockoutPartials/CoverArtistMessage.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/SongLockingAutoComplete.tsx, VocaDbWeb/Scripts/Components/Song/SongCreate.tsx, VocaDbWeb/Scripts/Components/Song/SongEdit.tsx, VocaDbWeb/Scripts/Stores/Song/SongCreateStore.ts
Fixes #1177.
Fixes #1180.
Fixes #1179.
=> Fix entry create and edit pages

VocaDbWeb/Scripts/Components/Song/SongEdit.tsx
=> Fix missing delete button on song edit page

VocaDbWeb/Scripts/App.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/LeftMenu.tsx, VocaDbWeb/Views/Shared/Partials/_LeftMenu.cshtml, VocaDbWeb/Views/Shared/React/Index.cshtml, VocaDbWeb/Views/Shared/_Layout.cshtml, VocaDbWeb/wwwroot/Content/Site.css, VocaDbWeb/wwwroot/Content/Styles/base.less
Inspired by [elastic/eui](https://github.com/elastic/eui).
=> Implement sticky side nav

VocaDbWeb/Program.cs
References:
- [Migrate from ASP.NET Core 5.0 to 6.0 | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#use-startup-with-the-new-minimal-hosting-model)
- [Getting started with ASP.NET Core 6 · NLog/NLog Wiki](https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-6#3-update-programcs)
=> Use Startup with the new minimal hosting model

VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx, VocaDbWeb/Scripts/Stores/Song/SongEditStore.ts
=> Preserve album ID

Tests/GitHubIssues/Issue1191/SongQueriesTests.cs, VocaDbModel/Database/Queries/SongQueries.cs
=> Fix SongQueries.Merge

VocaDbWeb/Scripts/DataContracts/Song/LyricsForSongContract.ts, VocaDbWeb/Scripts/Stores/Song/LyricsForSongListEditStore.ts, VocaDbWeb/Scripts/Stores/WebLinkEditStore.ts, VocaDbWeb/Scripts/ViewModels/Song/LyricsForSongEditViewModel.ts
=> #836: Autofill label from URL when adding lyrics to a song

VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx
=> Show save warning

VocaDbWeb/Scripts/JQueryUI/JQueryUIAutocomplete.tsx, VocaDbWeb/Scripts/JQueryUI/JQueryUIButton.tsx, VocaDbWeb/Scripts/JQueryUI/JQueryUICheckbox.tsx, VocaDbWeb/Scripts/JQueryUI/JQueryUIDatepicker.tsx
Possibly fixes VocaDB/community#160.
=> Improve integration with jQuery UI

VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/DropdownList.tsx
=> Set value to empty string

VocaDbWeb/Views/Shared/Partials/_LayoutScripts.cshtml
=> Fix LayoutScripts

VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/PV/EmbedPVPreview.tsx, VocaDbWeb/Scripts/Components/VdbPlayer/EmbedPV.tsx, VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayer.tsx, VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayerContext.tsx, VocaDbWeb/Scripts/Pages/Playlist/PlaylistIndex.tsx, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueStore.ts, VocaDbWeb/Scripts/index.tsx, VocaDbWeb/package-lock.json, VocaDbWeb/package.json
=> Switch between pv services

VocaDbWeb/Controllers/UserController.cs, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/DropdownList.tsx, VocaDbWeb/Scripts/DataContracts/ActivityEntry/ActivityEntryContract.ts, VocaDbWeb/Scripts/Models/ActivityEntries/EntryEditEvent.ts, VocaDbWeb/Scripts/Pages/ActivityEntry/ActivityEntryIndex.tsx, VocaDbWeb/Scripts/Pages/User/UserEntryEdits.tsx, VocaDbWeb/Scripts/Pages/User/UserOverview.tsx, VocaDbWeb/Scripts/Pages/User/UserRoutes.tsx, VocaDbWeb/Scripts/Stores/ActivityEntry/ActivityEntryListRouteParams.schema.json, VocaDbWeb/Scripts/Stores/ActivityEntry/ActivityEntryListStore.ts, VocaDbWeb/Scripts/ViewModels/ActivityEntry/ActivityEntryListViewModel.ts
=> Convert user entry edits to React

VocaDbWeb/Controllers/Api/IPRuleApiController.cs, VocaDbWeb/Controllers/Api/TagApiController.cs, VocaDbWeb/Controllers/Api/UserApiController.cs, VocaDbWeb/Controllers/Api/WebhookApiController.cs
Fixes #1239.
It looks like there was a breaking change in ASP.NET Core, which cannot be found in [Breaking changes in .NET 7](https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0).
TODO: Write integration tests.
=> Use FromBody attribute for HttpPut actions

VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/ArtistFilters.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/TagFilters.tsx, VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayer.tsx, VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayerContext.tsx, VocaDbWeb/Scripts/Pages/Playlist/PlaylistIndex.tsx, VocaDbWeb/Scripts/Repositories/SongRepository.ts, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueLocalStorageState.schema.json, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueRepository.ts, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueRepositoryForRatedSongsAdapter.ts, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueRepositoryForSongListAdapter.ts, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueRepositoryForSongsAdapter.ts, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueStore.ts, VocaDbWeb/Scripts/Stores/VdbPlayer/SkipListLocalStorageState.schema.json, VocaDbWeb/Scripts/Stores/VdbPlayer/SkipListStore.ts, VocaDbWeb/Scripts/Stores/VdbPlayer/VdbPlayerStore.ts
*Not to be confused with [Skip list](https://en.wikipedia.org/wiki/Skip_list).*
=> Implement skip list

VocaDbWeb/Scripts/Components/Shared/Partials/Activityfeed/ActivityEntryKnockout.tsx, VocaDbWeb/Scripts/DataContracts/ActivityEntry/ActivityEntryContract.ts
=> Make archivedVersion nullable

VocaDbWeb/Scripts/Components/KnockoutExtensions/AlbumAutoComplete.tsx, VocaDbWeb/Scripts/Components/KnockoutExtensions/ArtistAutoComplete.tsx, VocaDbWeb/Scripts/Components/KnockoutExtensions/SongAutoComplete.tsx, VocaDbWeb/Scripts/libs.js, VocaDbWeb/package-lock.json, VocaDbWeb/package.json
=> Remove unused libs

VocaDbWeb/Scripts/Pages/Home/HomeIndex.tsx, VocaDbWeb/Scripts/Shared/EntryUrlMapper.ts, VocaDbWeb/Scripts/main.tsx, VocaDbWeb/Scripts/vite-env.d.ts, VocaDbWeb/index.html, VocaDbWeb/package-lock.json, VocaDbWeb/package.json, VocaDbWeb/tsconfig.json, VocaDbWeb/tsconfig.node.json, VocaDbWeb/vite.config.ts
Closes #1102.
1. [Misskey](https://github.com/misskey-dev/misskey), a microblogging platform, migrated from Webpack to Vite recently (misskey-dev/misskey#8575).
2. @FinnRG suggested switching from Laravel Mix to Vite.
3. [TL;DR: esbuild is fast. Really fast.](https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/)
=> Install and configure Vite

Tests/Web/Controllers/DataAccess/UserQueriesTests.cs, VocaDbModel/DataContracts/Users/ServerOnlyUpdateUserSettingsForApiContract.cs, VocaDbWeb/Controllers/Api/UserApiController.cs, VocaDbWeb/Controllers/UserController.cs, VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/MainNavigationItems.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Shared/ValidationSummaryPanel.tsx, VocaDbWeb/Scripts/Pages/Album/AlbumCreate.tsx, VocaDbWeb/Scripts/Pages/Artist/ArtistCreate.tsx, VocaDbWeb/Scripts/Pages/Song/SongCreate.tsx, VocaDbWeb/Scripts/Pages/User/UserLogin.tsx, VocaDbWeb/Scripts/Pages/User/UserMySettings.tsx, VocaDbWeb/Scripts/Pages/User/UserRequestVerification.tsx, VocaDbWeb/Scripts/Pages/User/UserRoutes.tsx, VocaDbWeb/Scripts/Repositories/UserRepository.ts, VocaDbWeb/Scripts/Stores/User/UserLoginStore.ts
Reference(s):
- https://stackoverflow.com/questions/58157580/do-i-need-csrf-protection-for-login-endpoint
=> Convert user login to React

VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx, VocaDbWeb/Scripts/Models/NameMatchMode.ts, VocaDbWeb/Scripts/Repositories/AlbumRepository.ts, VocaDbWeb/Scripts/Repositories/ArtistRepository.ts, VocaDbWeb/Scripts/Repositories/BaseRepository.ts, VocaDbWeb/Scripts/Repositories/EntryRepository.ts, VocaDbWeb/Scripts/Repositories/ReleaseEventRepository.ts, VocaDbWeb/Scripts/Repositories/SongListRepository.ts, VocaDbWeb/Scripts/Repositories/SongRepository.ts, VocaDbWeb/Scripts/Repositories/TagRepository.ts, VocaDbWeb/Scripts/Repositories/UserRepository.ts, VocaDbWeb/Scripts/Stores/Comment/CommentListStore.ts, VocaDbWeb/Scripts/Stores/Search/AnythingSearchStore.ts, VocaDbWeb/Scripts/Stores/SongList/SongListsBaseStore.ts, VocaDbWeb/Scripts/Stores/User/ListUsersStore.ts
Related issue(s):
- https://github.com/VocaDB/vocadb/issues/1022#issuecomment-1094279316
=> Prevent full page refresh when using top search bar

VocaDbWeb/Controllers/Api/AntiforgeryApiController.cs, VocaDbWeb/Controllers/Api/UserApiController.cs, VocaDbWeb/Controllers/UserController.cs, VocaDbWeb/Scripts/Pages/User/UserCreate.tsx, VocaDbWeb/Scripts/Pages/User/UserForgotPassword.tsx, VocaDbWeb/Scripts/Pages/User/UserLogin.tsx, VocaDbWeb/Scripts/Pages/User/UserRoutes.tsx, VocaDbWeb/Scripts/Repositories/UserRepository.ts, VocaDbWeb/Scripts/Stores/User/UserForgotPasswordStore.ts, VocaDbWeb/Scripts/Stores/User/UserLoginStore.ts
=> Convert user forgot password to React

VocaDbWeb/Scripts/Components/VdbPlayer/VdbPlayer.tsx, VocaDbWeb/Scripts/Stores/VdbPlayer/PlayQueueStore.ts
=> Prevent videos from automatically playing when opening in a new tab

VocaDbWeb/Scripts/Components/KnockoutExtensions/TagAutoComplete.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/TagLockingAutoComplete.tsx, VocaDbWeb/Scripts/Models/Tags/TagTargetType.ts, VocaDbWeb/Scripts/Stores/Album/AlbumDetailsStore.ts, VocaDbWeb/Scripts/Stores/Artist/ArtistDetailsStore.ts, VocaDbWeb/Scripts/Stores/ReleaseEvent/EventSeriesDetailsStore.ts, VocaDbWeb/Scripts/Stores/ReleaseEvent/ReleaseEventDetailsStore.ts, VocaDbWeb/Scripts/Stores/Song/SongDetailsStore.ts, VocaDbWeb/Scripts/Stores/SongList/SongListStore.ts, VocaDbWeb/Scripts/Stores/Tag/TagsEditStore.ts
=> Fix tag search on event entries

VocaDbWeb/Code/Security/LogFileReader.cs, VocaDbWeb/Controllers/AdminController.cs
Fixes #1289,
Thanks, @snakefoot!
=> Use FileShare.ReadWrite

VocaDbWeb/Startup.cs, VocaDbWeb/VocaDbWeb.csproj
See also
- #1184 
- [Report](https://www.openbugbounty.org/reports/2814248/) by [LoveYad87478346](https://www.openbugbounty.org/researchers/LoveYad87478346/)
=> Welcome back, Swagger!

VocaDbModel/DataContracts/SongImport/ImportedSongListContract.cs, VocaDbModel/DataContracts/SongImport/PartialImportedSongs.cs, VocaDbModel/Service/SongImport/ISongListImporter.cs, VocaDbModel/Service/SongImport/KiitePlaylistImporter.cs
=> Feat/1297 add ability to import playlists from Kiite

Tests/Service/VideoServices/BilibiliHelperTests.cs, VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs
Closes https://github.com/VocaDB/community/issues/180
=> bilibili short link matchers

VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx
=> fix: Fix artist information not displaying correctly

VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx
=> fix: BaUserAlbumDate -> BaUseAlbumDate

VocaDbWeb/Scripts/Shared/WebLinkCategory.ts, VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts, VocaDbWeb/Scripts/Stores/Song/LyricsForSongListEditStore.ts, VocaDbWeb/Scripts/Stores/WebLinkEditStore.ts, VocaDbWeb/package-lock.json, VocaDbWeb/package.json
=> fix: Add youtube channel handle urls

VocaDbModel/Database/Queries/ActivityEntryQueries.cs, VocaDbWeb/Controllers/ActivityEntryController.cs, VocaDbWeb/Controllers/Api/ActivityEntryApiController.cs, VocaDbWeb/Scripts/Pages/ActivityEntry/ActivityEntryIndex.tsx, VocaDbWeb/Scripts/Pages/ActivityEntry/ActivityEntryRoutes.tsx, VocaDbWeb/Scripts/Pages/ActivityEntry/FollowedArtistActivity.tsx, VocaDbWeb/Scripts/Pages/Comment/CommentIndex.tsx, VocaDbWeb/Scripts/Stores/ActivityEntry/FollowedArtistActivityListStore.ts
Part of #1000.
TODO: Fix the "Load More" button
=> refactor: Convert activityEntries/followedArtistActivity to react 

VocaDbWeb/Controllers/Api/SongApiController.cs
=> fix: Default to empty array if no song types are given

Tests/Service/Search/AlbumSearch/AlbumSearchTests.cs, VocaDbModel/Service/AlbumService.cs, VocaDbModel/Service/QueryableExtensions/AlbumQueryableExtensions.cs, VocaDbModel/Service/Search/AlbumSearch/AlbumSearch.cs, VocaDbModel/Service/Search/AlbumSearch/ParsedAlbumQuery.cs
=> feat: Enable album crossfade searches and entry url searches

VocaDbWeb/Scripts/App.tsx
=> fix: Ignore unset stylesheet

VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx
=> fix: Clear globalSearchBox after quick navigation

VocaDbModel/Service/Security/SslHelper.cs
=> fix: Enable TLS 1.3

VocaDbWeb/Scripts/Components/Shared/KnockoutPartials/IPManage.tsx
=> fix: Update geoiptool url

VocaDbWeb/Scripts/Pages/Song/Partials/SongInListsDialog.tsx
=> fix: Show all lists

VocaDbWeb/Controllers/AdminController.cs, VocaDbWeb/Controllers/Api/AdminApiController.cs, VocaDbWeb/Scripts/DataContracts/PVForSongContract.ts, VocaDbWeb/Scripts/DataContracts/PVs/PVContract.ts, VocaDbWeb/Scripts/Pages/Admin/AdminPVsByAuthor.tsx, VocaDbWeb/Scripts/Pages/Admin/AdminRoutes.tsx, VocaDbWeb/Scripts/Repositories/AdminRepository.ts
=> refactor: Convert PVsByAuthor to React

VocaDbWeb/Scripts/Repositories/SongRepository.ts, VocaDbWeb/Scripts/Stores/Song/SongDetailsStore.ts
=> fix: Get optional main thumb for related songs

VocaDbWeb/Scripts/Components/Shared/GlobalSearchBox.tsx
Fixes #1462. Bug was introduced with #1434.
=> Fix: jQuery UI autocomplete

VocaDbWeb/Scripts/Components/Shared/Partials/PV/EmbedPiapro.tsx
=> fix: Use html5 iframes for piapro embeds

VocaDb.Migrations/Migrations.cs, VocaDb.Migrations/TableNames.cs, VocaDbModel/DataContracts/Songs/SongDetailsForApiContract.cs, VocaDbModel/DataContracts/Songs/SongForApiContract.cs, VocaDbModel/DataContracts/Songs/SongForEditForApiContract.cs, VocaDbModel/Database/Queries/SongQueries.cs, VocaDbModel/Domain/Songs/LyricsForSong.cs, VocaDbModel/Domain/Songs/Song.cs, VocaDbModel/Domain/Songs/SongDiff.cs, VocaDbModel/Domain/Songs/SongEditableFields.cs, VocaDbModel/Mapping/Songs/LyricsForSongMap.cs, VocaDbModel/Mapping/Songs/SongMap.cs, VocaDbModel/Service/QueryableExtensions/SongLinkQueryableExtensions.cs, VocaDbModel/Service/QueryableExtensions/SongQueryableExtensions.cs, VocaDbWeb/Scripts/DataContracts/Song/SongDetailsContract.ts, VocaDbWeb/Scripts/DataContracts/Song/SongDetailsForApi.ts, VocaDbWeb/Scripts/DataContracts/Song/SongForEditContract.ts, VocaDbWeb/Scripts/Pages/Song/SongBasicInfo.tsx, VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx, VocaDbWeb/Scripts/Stores/CultureCodesEditStore.ts, VocaDbWeb/Scripts/Stores/Song/LyricsForSongListEditStore.ts, VocaDbWeb/Scripts/Stores/Song/SongEditStore.ts, VocaDbWeb/public/locales/en/ViewRes.Song.json
=> Song entry: New field for language

VocaDbWeb/Startup.cs, VocaDbWeb/VocaDbWeb.csproj
Currently we have no insight into average request volume and average latency. This PR adds Prometheus metrics to give better insight into the performance of the backend.
=> feat: Prometheus metrics for better observability

VocaDbModel/Service/UserService.cs, VocaDbWeb/Scripts/Components/Shared/KnockoutPartials/IPManage.tsx, VocaDbWeb/Scripts/Pages/User/UserOverview.tsx, VocaDbWeb/Views/Shared/KnockoutPartials/_IPManage.cshtml, VocaDbWeb/Views/User/Details.cshtml
=> fix: Update geoiptool

VocaDbModel/DataContracts/Artists/AdvancedArtistStatsContract.cs, VocaDbModel/Database/Queries/ArtistQueries.cs, VocaDbModel/Service/Queries/ArtistRelationsQuery.cs, VocaDbWeb/Scripts/DataContracts/Artist/ArtistDetailsContract.ts, VocaDbWeb/Scripts/Pages/Artist/ArtistBasicInfo.tsx, VocaDbWeb/public/locales/en/Resources.json, VocaDbWeb/public/locales/en/ViewRes.Artist.json
Closes #1409. Based on #1415 and includes the newly added language field.
=> feat: Extend advanced stats with top languages

VocaDbWeb/package-lock.json, VocaDbWeb/package.json
=> chores: Update react router

VocaDbModel/DataContracts/Songs/SongInAlbumForApiContract.cs, VocaDbWeb/Controllers/Api/SongApiController.cs, VocaDbWeb/Scripts/DataContracts/Album/AlbumDetailsForApi.ts, VocaDbWeb/Scripts/DataContracts/Song/SongInAlbumContract.ts, VocaDbWeb/Scripts/Pages/Album/AlbumBasicInfo.tsx, VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx, VocaDbWeb/Scripts/Stores/Song/SongEditStore.ts
=> feat: More language field improvements

VocaDbWeb/Scripts/Components/Shared/Partials/MainNavigationItems.tsx, VocaDbWeb/public/locales/en/ViewRes.json
=> fix: Remove the "Blog" link

VocaDbWeb/Startup.cs, VocaDbWeb/VocaDbWeb.csproj
Migrating from prometheus-net to OTEL metrics.
=> Better observability

VocaDbWeb/Controllers/ActivityEntryController.cs, VocaDbWeb/Controllers/AdminController.cs, VocaDbWeb/Controllers/AlbumController.cs, VocaDbWeb/Controllers/ArtistController.cs, VocaDbWeb/Controllers/CommentController.cs, VocaDbWeb/Controllers/ControllerBase.cs, VocaDbWeb/Controllers/DiscussionController.cs, VocaDbWeb/Controllers/ErrorController.cs, VocaDbWeb/Controllers/EventController.cs, VocaDbWeb/Controllers/HelpController.cs, VocaDbWeb/Controllers/HomeController.cs, VocaDbWeb/Controllers/PlaylistController.cs, VocaDbWeb/Controllers/SearchController.cs, VocaDbWeb/Controllers/SongController.cs, VocaDbWeb/Controllers/SongListController.cs, VocaDbWeb/Controllers/StatsController.cs, VocaDbWeb/Controllers/TagController.cs, VocaDbWeb/Controllers/UserController.cs, VocaDbWeb/Controllers/VenueController.cs, VocaDbWeb/Helpers/ReactIndex.cs, VocaDbWeb/Startup.cs, VocaDbWeb/index.html
=> feat: Add metadata back

Tests/Web/Controllers/DataAccess/UserQueriesTests.cs, VocaDbModel/Database/Queries/UserQueries.cs, VocaDbModel/Service/Security/PKBDF2PasswordHashAlgorithm.cs, VocaDbModel/Service/Security/PasswordHashAlgorithms.cs, VocaDbModel/VocaDb.Model.csproj
=> fix(crypto): Update to PKBDF2

VocaDbModel/Service/QueryableExtensions/ArtistQueryableExtensions.cs, VocaDbModel/Service/QueryableExtensions/SongQueryableExtensions.cs, VocaDbModel/Service/Search/Artists/ArtistQueryParams.cs, VocaDbModel/Service/Search/Artists/ArtistSearch.cs, VocaDbModel/Service/Search/SongSearch/SongQueryParams.cs, VocaDbModel/Service/Search/SongSearch/SongSearch.cs, VocaDbWeb/Controllers/Api/ArtistApiController.cs, VocaDbWeb/Controllers/Api/SongApiController.cs, VocaDbWeb/Scripts/Components/extendedUserLanguageCultures.ts, VocaDbWeb/Scripts/Pages/Album/AlbumBasicInfo.tsx, VocaDbWeb/Scripts/Pages/Search/Partials/ArtistSearchOptions.tsx, VocaDbWeb/Scripts/Pages/Search/Partials/SongSearchOptions.tsx, VocaDbWeb/Scripts/Pages/Song/Partials/LyricsForSongEdit.tsx, VocaDbWeb/Scripts/Repositories/ArtistRepository.ts, VocaDbWeb/Scripts/Repositories/SongRepository.ts, VocaDbWeb/Scripts/Stores/Search/ArtistSearchStore.ts, VocaDbWeb/Scripts/Stores/Search/SongSearchStore.ts, VocaDbWeb/package.json
=> More language field improvements

VocaDb.Migrations/Migrations.cs, VocaDbModel/Mapping/Tags/TagMap.cs
=> fix: Increase ChangedFields length

VocaDbWeb/New/next.config.js, VocaDbWeb/Startup.cs, VocaDbWeb/VocaDbWeb.csproj
Implements special cases for the development environment and fixes the nextjs server location for `dotnet publish`.
=> fix: Various nextjs server fixes

VocaDbWeb/New/components/AppShell/Header.tsx, VocaDbWeb/New/components/AppShell/Navbar.tsx, VocaDbWeb/New/components/ColorSchemeToggle/ColorSchemeToggle.tsx, VocaDbWeb/New/components/Context/ThemeContext.tsx, VocaDbWeb/New/components/Frontpage/HighlightedSongCard.tsx, VocaDbWeb/New/components/Frontpage/HighlightedSongsCarousel.tsx, VocaDbWeb/New/components/Welcome/Welcome.styles.ts, VocaDbWeb/New/components/Welcome/Welcome.tsx, VocaDbWeb/New/next.config.js, VocaDbWeb/New/package-lock.json, VocaDbWeb/New/package.json, VocaDbWeb/New/pages/_app.tsx, VocaDbWeb/New/pages/index.tsx
=> feat: Improved highlighted PVs

VocaDbWeb/Controllers/HomeController.cs, VocaDbWeb/New/components/ColorSchemeToggle/ColorSchemeToggle.tsx, VocaDbWeb/New/next.config.js, VocaDbWeb/Program.cs, VocaDbWeb/appsettings.json
Various potential beta routing fixes.
=> fix: New beta routing fixes

VocaDbModel/Service/QueryableExtensions/EntryWithTagsQueryableExtensions.cs, VocaDbModel/Service/QueryableExtensions/SongQueryableExtensions.cs, VocaDbModel/Service/Search/SongSearch/SongQueryParams.cs, VocaDbModel/Service/Search/SongSearch/SongSearch.cs, VocaDbWeb/Controllers/Api/SongApiController.cs, VocaDbWeb/Scripts/Components/Shared/Partials/TagFiltersBase.tsx, VocaDbWeb/Scripts/Repositories/SongRepository.ts, VocaDbWeb/Scripts/Stores/Search/SearchCategoryBaseStore.ts, VocaDbWeb/Scripts/Stores/Search/SongSearchStore.ts, VocaDbWeb/Scripts/Stores/Search/TagFilter.ts, VocaDbWeb/Scripts/Stores/Search/TagFilters.ts
Closes https://github.com/VocaDB/vocadb/issues/1332. I still have to work out the best UI for this, so maybe this will only be supported in the new frontend.
=> feat: Allow users to exclude tags in the search

VocaDbWeb/Scripts/Helpers/AjaxHelper.ts, VocaDbWeb/Scripts/Pages/Artist/ArtistBasicInfo.tsx, VocaDbWeb/Scripts/Pages/Search/Partials/ArtistSearchOptions.tsx, VocaDbWeb/public/locales/en/ViewRes.Artist.json
=> Various search and language field fixes

VocaDbWeb/Scripts/Components/extendedUserLanguageCultures.ts, VocaDbWeb/Scripts/Pages/User/UserMySettings.tsx, VocaDbWeb/Scripts/Pages/User/UserOverview.tsx, VocaDbWeb/Scripts/Stores/User/MySettingsStore.ts, VocaDbWeb/public/locales/en/ViewRes.User.json
=> feat: Allow language extension for user known languages

VocaDb.Migrations/Migrations.cs, VocaDb.Migrations/TableNames.cs, VocaDbModel/DataContracts/Songs/SongDetailsForApiContract.cs, VocaDbModel/DataContracts/Songs/SongForApiContract.cs, VocaDbModel/DataContracts/Songs/SongForEditForApiContract.cs, VocaDbModel/Database/Queries/SongQueries.cs, VocaDbModel/Domain/Songs/Song.cs, VocaDbModel/Mapping/ReleaseEvents/ReleaseEventMap.cs, VocaDbModel/Mapping/Songs/SongMap.cs, VocaDbModel/Service/QueryableExtensions/SongQueryableExtensions.cs, VocaDbWeb/Scripts/Components/Shared/Partials/Knockout/ReleaseEventsEditView.tsx, VocaDbWeb/Scripts/DataContracts/Song/SongDetailsContract.ts, VocaDbWeb/Scripts/DataContracts/Song/SongDetailsForApi.ts, VocaDbWeb/Scripts/DataContracts/Song/SongForEditContract.ts, VocaDbWeb/Scripts/Pages/Song/SongBasicInfo.tsx, VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx, VocaDbWeb/Scripts/Stores/Song/SongEditStore.ts
=> feat: Multiple release events for albums/songs

VocaDbModel/Service/Search/AlbumSearch/AlbumSearch.cs, VocaDbModel/Service/Search/AlbumSearch/ParsedAlbumQuery.cs, VocaDbWeb/Controllers/ArtistController.cs
Updates AlbumSearch.cs to respect exact searches (defined in https://wiki.vocadb.net/wiki/33/search-terms-cheat-sheet)
=> fix: Exact album search

VocaDbWeb/Scripts/Stores/WebLinksEditStore.ts
=> fix: Smaller frontend fixes

VocaDb.Migrations/Migrations.cs, VocaDbModel/DataContracts/PVs/PVContract.cs, VocaDbModel/Domain/Albums/Album.cs, VocaDbModel/Domain/Albums/PVForAlbum.cs, VocaDbModel/Mapping/Albums/PVForAlbumMap.cs, VocaDbModel/Service/SongService.cs, VocaDbWeb/Scripts/Components/Shared/Partials/Shared/FormatPVLink.tsx, VocaDbWeb/Scripts/Stores/Album/AlbumEditStore.ts, VocaDbWeb/Scripts/Stores/PVs/PVListEditStore.ts
=> feat: Allow marking crossfades as unavailable

VocaDbModel/Service/VideoServices/NicoLogParser.cs
=> fix: Proxy nicolog requests over dream-traveler

VocaDbWeb/Helpers/OriginValidationFilter.cs
=> fix: Update OriginValidationFilter

VocaDbModel/Database/Queries/StatsQueries.cs, VocaDbWeb/Controllers/StatsController.cs
Adds a new endpoint to fetch song hit data.
=> feat: Improve existing stats APIs

VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts, VocaDbWeb/Scripts/styles/ExtLinks.css
=> chores: Add more URL matchers

VocaDbWeb/Controllers/Api/EntryApiController.cs
=> fix: Include tags in anything search category

VocaDbWeb/Scripts/Pages/Artist/ArtistEdit.tsx
=> fix: Add Utaite to voice provider dropdown artist types

VocaDbWeb/Scripts/styles/Styles/base.less
=> fix: Increase entry description width

VocaDbWeb/Scripts/Components/KnockoutExtensions/ReleaseEventAutoComplete.tsx
Implements the suggestion from #1603 to add event dates to release event dropdowns.
=> feat: Add event dates to event dropdown

VocaDbModel/Database/Queries/ActivityEntryQueries.cs
Fixes #1597. #1256 will replace this fix in the long term.
=> fix: Use local timezone for the before parameter

VocaDbWeb/Scripts/Components/Shared/Partials/Artist/ArtistList.tsx
=> fix: Remove space before vocalist artists

VocaDbWeb/Controllers/Api/TagApiController.cs, VocaDbWeb/Controllers/TagController.cs, VocaDbWeb/Scripts/Repositories/TagRepository.ts, VocaDbWeb/Scripts/Stores/Tag/DeletedTagsStore.ts, VocaDbWeb/Scripts/route-sphere/components/useLocationStateHandler.tsx
Fixes issues with songlist items flickering and the `/Tag/Deleted` page not working correctly.
=> hotfix: /Tags/Deleted and songlist flickering

VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts, VocaDbWeb/Scripts/styles/ExtLinks.css
=> chores: New weblink matchers

VocaDbWeb/Helpers/OriginValidationFilter.cs
This should make frontend developmnent on two different hosts easier.
=> fix: Trust localhost with restricted APIs

VocaDbModel/DataContracts/Users/UserRewindForApiContract.cs, VocaDbModel/Database/Queries/UserQueries.cs, VocaDbWeb/Controllers/Api/UserApiController.cs
This PR will only add the necessary backend code for various user stats needed for VocaDB Wrapped 2023. The video render code will be added in a separate PR.
=> feat: New APIs for VocaDB Wrapped 2023

VocaDbModel/Database/Queries/ArtistQueries.cs
=> fix: Update artistString of albums on name change

VocaDbWeb/Scripts/AppRoutes.tsx, VocaDbWeb/Scripts/Pages/Rewind/Rewind.tsx, VocaDbWeb/Scripts/Pages/Rewind/RewindRoutes.tsx
This PR adds the necessary code for vocadb rewind. The main animation code lives in a [separate repo](https://github.com/Finnrg/vocadb-rewind). VocaDB only renders the external page as an iframe.
=> feat: VocaDB rewind frontend

VocaDbModel/Database/Queries/AlbumQueries.cs
=> fix: Multiple fixes for album reverts

VocaDbWeb/Scripts/Components/Shared/Partials/Album/PrintArchivedAlbumData.tsx, VocaDbWeb/Scripts/DataContracts/Album/ArchivedAlbumContract.ts
Fixes crashes of AlbumViewVersion on old album entries (i.e. https://vocadb.net/Album/ViewVersion/1728).
=> fix: Account for undefined identifiers

VocaDbWeb/Scripts/Pages/SongList/SongListEdit.tsx
=> fix: Account for CRLF line endings

VocaDbModel/Database/Queries/ActivityEntryQueries.cs, VocaDbWeb/Helpers/ReactIndex.cs, VocaDbWeb/Scripts/Pages/Admin/AdminPVsByAuthor.tsx, VocaDbWeb/Scripts/Stores/Album/AlbumDetailsStore.ts, VocaDbWeb/index.html
Fixes #1662 and #1663 and other smaller API bugs.
=> fix: API bugs

VocaDbModel/Database/Queries/SongListQueries.cs, VocaDbModel/Database/Queries/UserQueries.cs, VocaDbModel/Domain/Songs/SongList.cs, VocaDbWeb/Scripts/Pages/SongList/SongListEdit.tsx
=> fix: Better CSV import

VocaDbModel/Database/Queries/UserQueries.cs, VocaDbWeb/Scripts/Helpers/DateTimeHelper.ts, VocaDbWeb/Scripts/Pages/Home/HomeIndex.tsx, VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx, VocaDbWeb/Scripts/styles/Site.css
Fixes #1324 and restores the original highlighted PV's section height.
=> fix: Date button timezone

VocaDbModel/Database/Queries/SongQueries.cs
=> fix: Set default for URL in restore to empty string

VocaDbWeb/Scripts/Components/Shared/Partials/MainNavigationItems.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Shared/FormatPVLink.tsx, VocaDbWeb/Scripts/Pages/Home/HomeIndex.tsx, VocaDbWeb/Scripts/Pages/Song/SongBasicInfo.tsx, VocaDbWeb/Scripts/Pages/Song/SongEdit.tsx, VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts, VocaDbWeb/Scripts/Stores/Album/AlbumEditStore.ts, VocaDbWeb/Scripts/Stores/Song/SongEditStore.ts, VocaDbWeb/Scripts/styles/Site.css
=> fix: Frontend fixes 2024 week 6

VocaDbModel/Database/Queries/AlbumQueries.cs, VocaDbModel/Database/Queries/SongQueries.cs, VocaDbModel/Domain/Tags/TagManager.cs, VocaDbModel/Service/ArtistService.cs
=> fix: Move tags on merge

VocaDbModel/Service/VideoServices/PiaproClient/PiaproClient.cs, VocaDbModel/Service/VideoServices/PiaproClient/PiaproException.cs, VocaDbModel/Service/VideoServices/PiaproClient/PiaproParser.cs, VocaDbModel/Service/VideoServices/PiaproClient/PiaproUrlHelper.cs, VocaDbModel/Service/VideoServices/PiaproClient/PostQueryResult.cs, VocaDbModel/Service/VideoServices/VideoServicePiapro.cs, VocaDbModel/VocaDb.Model.csproj, VocaDbWeb/Scripts/Components/Shared/Partials/PV/EmbedPiapro.tsx
=> fix: Update Piapro parser code

VocaDbModel/DataContracts/Artists/ArtistDetailsForApiContract.cs, VocaDbWeb/Scripts/DataContracts/Artist/ArtistDetailsContract.ts, VocaDbWeb/Scripts/Pages/Artist/ArtistBasicInfo.tsx, VocaDbWeb/Scripts/i18n.ts
=> fix: Multiple character designers

VocaDbModel/Service/VideoServices/PiaproClient/PiaproParser.cs, VocaDbWeb/Scripts/i18n.ts
Another piapro layout change. Let's hope that this will be the last one for now. Fixes #1704.
=> fix: Piapro layout change

VocaDbWeb/Scripts/Components/Shared/ArtistPopupContent.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Song/SongGrid.tsx, VocaDbWeb/Scripts/Components/Shared/SongPopupContent.tsx, VocaDbWeb/Scripts/Pages/Artist/ArtistBasicInfo.tsx, VocaDbWeb/Scripts/Pages/Song/SongRankings.tsx, VocaDbWeb/Scripts/Pages/SongList/SongListDetails.tsx, VocaDbWeb/Scripts/i18n.ts
=> fix: Use UTC for publish and release dates 

VocaDbWeb/Scripts/Components/Shared/Partials/Song/SongListsKnockout.tsx, VocaDbWeb/Scripts/Pages/Event/EventDetails.tsx, VocaDbWeb/Scripts/Pages/Event/EventSeriesDetails.tsx, VocaDbWeb/Scripts/Pages/SongList/SongListFeatured.tsx, VocaDbWeb/Scripts/i18n.ts
This PR fixes various issues with date and time conversions for release and event dates. Many thanks to @szhublox for finding these.
=> fix: Use UTC for release and event dates

VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts
https://discord.com/channels/309072240639737866/818499255349018624/1219306519204462623
=> Add new linkmatchers

VocaDbWeb/Scripts/Components/extendedUserLanguageCultures.ts
=> chores: add Old English, Kazakh

VocaDbWeb/Scripts/Shared/WebLinkMatcher.ts, VocaDbWeb/Scripts/styles/ExtLinks.css
=> chores: New web link matchers

VocaDbModel/Mapping/ReleaseEvents/ReleaseEventMap.cs, VocaDbWeb/Scripts/Pages/Event/EventEdit.tsx
=> feat: Increase event description length

VocaDbModel/Service/SongImport/NicoNicoMyListParser.cs, VocaDbModel/Utils/AppConfig.cs, VocaDbWeb/Controllers/Api/PVApiController.cs
This PR adds a common user agent to various NND requests. This mainly fixes the NND playlist import feature.
=> fix: NND Playlist import

VocaDbModel/Service/VideoServices/VideoServiceSoundCloud.cs
=> fix: Use dream traveler for SC

VocaDbWeb/Controllers/HomeController.cs
=> fix: Set og:title for /Home

VocaDbModel/Service/VideoServices/VideoServiceBilibili.cs
=> fix: Change aid type from int to long

VocaDbModel/Database/Queries/UserQueries.cs
=> fix: Filter deleted tags in GetFavoriteTagIds

VocaDbWeb/Scripts/Components/Shared/Partials/Comment/CommentBodyLarge.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/CommentKnockout.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/Comment/PrintComment.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/User/UserIconLink_UserForApiContract.tsx, VocaDbWeb/Scripts/Components/Shared/Partials/User/UserLink.tsx
=> feat: Indicate user group with color in comments

VocaDbWeb/Scripts/Components/Shared/Partials/Shared/DraftMessage.tsx, VocaDbWeb/Scripts/Pages/Error/ErrorIndex.tsx, VocaDbWeb/Scripts/Pages/User/UserDetails.tsx
=> fix: Update wiki links

VocaDbWeb/Scripts/Pages/Stats/StatsIndex.tsx, VocaDbWeb/Scripts/Stores/StatsStore.ts
=> fix: Time selector in /stats doesn't update charts

VocaDbModel/Service/OtherService.cs, VocaDbModel/Service/QueryableExtensions/ReleaseEventQueryableExtensions.cs
=> fix: Include ongoing events for the "Happening now section"

VocaDbModel/Service/Helpers/TagFactory.cs
=> fix: Set default name language to unspecified for tags

VocaDbWeb/Scripts/Pages/Artist/ArtistBasicInfo.tsx
for clarity on entries for voicebanks such as [ずんだもん (Unknown)](https://vocadb.net/Ar/119812) which are on multiple engines
----
discussion:
- https://discord.com/channels/309072240639737866/666326527197315091/1330359327017664602
- https://discord.com/channels/309072240639737866/666326527197315091/1330380266098786425
=> feat: Add type label to the base voicebank and child voicebank lists

VocaDbWeb/Scripts/Components/extendedUserLanguageCultures.ts
=> chore: Add Evenki
